
// ORDERS
export const GET_ORDERS = 'GET_ORDERS';
export const GET_SINGLE_ORDER = 'GET_SINGLE_ORDER';

// SCHEDULES
export const GET_SCHEDULES = 'GET_SCHEDULES';


// BOOKINGS
export const GET_BOOKING_BY_ID = 'GET_BOOKING_BY_ID';
export const SUCCESS_BOOKING = 'SUCCESS_BOOKING';

// RESOURCES
export const GET_RESOURCES_SORTED_BY_TYPE = 'GET_RESOURCES_SORTED_BY_TYPE';
export const GET_RESOURCES_NOT_SORTED = 'GET_RESOURCES_NOT_SORTED';
export const GET_RESOURCE_DETAILED = 'GET_RESOURCE_DETAILED';

export const GET_RESOURCE_BY_ID = 'GET_RESOURCE_BY_ID';
export const CLEAR_CURRENT_RESOURCE = 'CLEAR_CURRENT_RESOURCE';

// USERS
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_USERS_LIST_BY_PROJECT = 'GET_USERS_LIST_BY_PROJECT';
export const GET_USER_INFO = 'GET_USER_INFO';
export const INVITATION_SENT = 'INVITATION_SENT';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const EMAIL_NOTIFICATIONS_SETTINGS = 'EMAIL_NOTIFICATIONS_SETTINGS';

// PROJECTS
export const GET_PROJECTS_LIST = 'GET_PROJECTS_LIST';
export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT';
export const GET_PROJECT_BY_ID = 'GET_PROJECT_BY_ID';
export const GET_PROJECT_INFO_BY_ID = 'GET_PROJECT_INFO_BY_ID';

//CONTACTS
export const GET_PROJECT_CONTACTS_BY_ID = 'GET_PROJECT_CONTACTS_BY_ID';
export const GET_CONTACT_DETAILED = 'GET_CONTACT_DETAILED';

// LOADING indicator
export const LOADING_DATA = 'LOADING_DATA';

// CALENDAR
export const SELECT_OPEN = 'SELECT_OPEN';
export const GET_CALENDAR_SCHEDULES = 'GET_CALENDAR_SCHEDULES';

// NETWORK ERROR
export const CREATE_USER_NETWORK_ERROR = 'CREATE_USER_NETWORK_ERROR';
export const LOGIN_NETWORK_ERROR = 'LOGIN_NETWORK_ERROR';
export const CREATE_BOOKING_NETWORK_ERROR = 'CREATE_BOOKING_NETWORK_ERROR';
export const CHANGE_PASSWORD_NETWORK_ERROR = 'CHANGE_PASSWORD_NETWORK_ERROR';
export const RESET_PASSWORD_NETWORK_ERROR = 'RESET_PASSWORD_NETWORK_ERROR';
export const USER_NETWORK_ERROR = 'USER_NETWORK_ERROR';

// LOGIN
export const IS_LOGIN = 'IS_LOGIN';
